services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgresql:/docker-entrypoint-initdb.d
      - ./db/backups:/var/tmp/backups

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
