services:
  address_postgres:
    image: postgres:latest
    container_name: address_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgresql:/docker-entrypoint-initdb.d
      - ./db/backups:/var/tmp/backups

  web:
    build: .
    container_name: address_api
    ports:
      - "5000:8000"
    depends_on:
      - address_postgres
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
