# Test your FastAPI endpoints

GET http://127.0.0.1:8000/address/68512644
Accept: application/json

###

GET http://127.0.0.1:8000/geolocation/distance/from/68512644/to/01001901
Accept: application/json

###
